#!/bin/bash

echo "Installing JupyterLab extensions from extensions-pip.txt..."
pip install --no-cache-dir -r extensions-pip.txt

echo "Enabling JupyterLab extensions..."
jupyter lab build

echo "Verifying JupyterLab extensions..."
jupyter labextension list

echo "Setup complete. Environment is ready!"
